### ISSUE TITLE
mozilla fixed this, extension no longer needed

### ISSUE THREAD

**Issue by ghost** [jscher2000/cache-favicons-for-bookmarks-extension#1]
I reported this and they fixed it, OK, tested it on Firefox Nightly 74.0a1 and they fixed it. Your extension is now obsolete and not needed.
mbasic.facebook.com and basic mail.google.com now work properly, although I had to wait about a day probably for cache to refresh those icons in bookmarks, although I immediately cleared all cache and restarted browser. Now all icon display properly even without your extension.

**Comment by MarkyMarkDE** [comment]
no, this Bug is present in Firefox ESR 102.10.x branch.
Here you must delete your `favicons.sqlite` in profile folder and rebuild the sqlite-file complete with e.g. Checkmarks Add-on. But unfortunately this Add-on can't grab really all favicons, for this I use this Add-on here and this have additional problem with some of the favicons on my bookmarks by unknown reasons.
See Bug Report [#7](https://github.com/jscher2000/cache-favicons-for-bookmarks-extension/issues/7)
